### ISSUE TITLE
Recommended slicer for .stl?

### ISSUE THREAD

**Issue by bam54** [poppy-project/poppy-ergo-jr#55]
Hi,

I'm trying to slice the .stl files into .gcode and have been using Cura version 3.1.0.  Cura isn't able to open any of the .stl files though, returning a vague error message that says, "Failed to load {path to file}".  Has anyone else had this problem?  If not, what slicer did you use?

**Comment by show0k** [comment]
Hi,
The issue doesn't come from cura, but in the way you downloaded the file. If you take the stl from the git tree, you should install git-lfs. Otherwise it's only a text file with a link inside. The easier is to download the STL zip from the [relsease](https://github.com/poppy-project/poppy-ergo-jr/releases/tag/1.0.0-gm).

**Comment by bam54** [comment]
Thanks!
