### ISSUE TITLE
Issue with using U2D2 to control Poppy Ergo directly

### ISSUE THREAD

**Issue by vantony1** [poppy-project/poppy-ergo-jr#64]
Hello,

I have successfully been able to connect the 6 ergo jr motors with a u2d2 ftdi and have checked its functioning using herborist as suggested. 

However, when I try to create a robot using your python library [poppy = PoppyErgoJr()] I get the following error: OSError: Could not initialize robot: [Errno 2] could not open port /dev/ttyAMA0: [Errno 2] No such file or directory: '/dev/ttyAMA0'

The problem I think is that the u2d2 is connect to ttyUSB0 as verified by command "dmesg | grep FTDI".

Do you have any suggestions on how to fix this? Any help would be very much appreciated :))

P.S. while working on this project, we found that printing the lamp head for the Ergo either resulted in a weak motor connector part or a weak lamp shade dependent on the orientation of the lamp head. One of my teammate designed and printed a two part version of the lamp head that is significantly stronger and we were wondering if you'd be interested in seeing it and maybe including it with the ergo cad files as an option?

**Comment by ymollard** [comment]
Change the configuration file in order to open the right port. Consult the [following documentation](https://docs.poppy-project.org/en/programming/edit-robot-behaviour.html#use-a-different-serial-port--use-a-different-ftdi-such-as-u2d2)

Feel free to document your custom lamp shade on [the forum](http://forum.poppy-project.org/) with your CAD link or file! You can also quote @poppy_project on Twitter with pictures, and a link to your thread on the forum.

Also, please use the forum to request help. By this way, any user could answer to your request. Keep Github issues only to report bugs.
